---
name: helm
on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: set up helm
        uses: azure/setup-helm@v4

      - uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: set up chart-testing
        uses: helm/chart-testing-action@v2.8.0

      - name: run chart-testing (lint)
        run: ct lint --all

      - name: create kind cluster
        uses: helm/kind-action@v1.14.0

      - name: run chart-testing (install)
        run: ct install --all

  release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/feat/multitenancy-support' }}
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: set up helm
        uses: azure/setup-helm@v4
        with:
          version: v3.13.0

      - name: login to github container registry using helm
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io/snapp-incubator/soteria --username ${{ github.repository_owner }} --password-stdin

      - name: package soteria helm chart
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            version=${{ github.ref_name }}
            helm package --version "${version##v}" --app-version "${version}" ./charts/soteria
          else
            helm package --version "0.0.0-multitenancy" --app-version "multitenancy" ./charts/soteria
          fi

      - name: publish soteria chart to github container registry
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            version=${{ github.ref_name }}
            helm push "soteria-${version##v}.tgz" oci://ghcr.io/snapp-incubator/soteria-chart
          else
            helm push "soteria-0.0.0-multitenancy.tgz" oci://ghcr.io/snapp-incubator/soteria-chart
          fi
